### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by odineiramone** [darlanmendonca/bash-basics#11]
Notei isso no fork to bash-basics, no Github a "ancora" do menu com o comando funciona, mas no editor de texto não. Ficou um pouco confuso procurar os comandos mesmo com um CTRL+F. Ajudaria muito estar em ordem alfabética.

Me proponho a fazer isso no bash basics mas gostaria de mais opiniões.

**Comment by darlanmendonca** [comment]
Opa @OdineiRibeiro, vlw pelo help, vi suas Issues e PR's.

Creio que ficaria bem bacana uma ordem alfabética, poderá auxiliar pacas. Somente precisamos ver um lance que estamos discutindo nessa https://github.com/knowledge-club/bash-basics/issues/9

Tipo assim, dará mto conflito e dificultará o code review, se fizermos um SFA (Single File Application), rs.

Estamos pensando em colocar no início do README apenas os comandos realmente básicos, para facilitar para novos devs e n demandar um tempo enorme d leitura. Se o kra quiser aprender mais, ele vai voltando no repo e aprendendo continuamente novos comandos, talvez até um watch no repo. 
E também no readme, mas abaixo da lista basica, ou um link para outro markdown, ond consta a lista em ordem alfabética, dos demais comandos.

Isto irá gerar escopos melhores, e melhorar o code review. E evitar conflitos de erros.

Há, outra coisa, kda PR, será de apenas um comando, tbm pra facilitar code review, e evitar conflitos.

Vou fazer o contributing, daí mandamos bala, blz?

**Comment by odineiramone** [comment]
@darlanmendonca, vou ver o #9 mas, a principio, posso organizar os comandos já existentes?

E, sobre o PR, vou refazer ele por comando, beleza?

**Comment by darlanmendonca** [comment]
sobre o PR, faz por comando, e aloca em arquivo separado, dawe não corre risco de perder nenhum trampo

dá uma lida aqui antes https://github.com/knowledge-club/bash/issues/13, pra n ter erro :D

**Comment by khaosdoctor** [comment]
Mas as ancoras são os mesmos títulos dos menus... O `ctrl+f` deveria funcionar nesse caso...

A gente estava tendo uma discussão sobre ordem na #3, decidimos organizar por complexidade, mas de acordo com a nova especificação de organização acho que essa ordem alfabética pode ser apenas necessário no README.

**Comment by darlanmendonca** [comment]
e sipa vamos colocar no readme, apenas
- comandos realmente básicos, estes creio q em ordem de complexidade
- link para summary.md
- mention to contributing

já neste summary, staria o restante dos comandos, e estes, ordenados por ordem alfabética
summary seria editado apenas por membros da organization, para evitar conflitos em merges, e trabalho c o mesmo

confere? @khaosdoctor

**Comment by khaosdoctor** [comment]
Eu acho melhor não ter esses comandos no Readme... O Readme seria realmente **só** o sumário, porque aí a gente divide muito as partes e pode ser que alguém mande PR em mais de um arquivo e vê ré conflitos. Os comandos manteremos mesmo em arquivos separados, eu pelo menos acho melhor

**Comment by darlanmendonca** [comment]
nenhum comando no readme? e dawe eles serao listados num summary.md? ou dois (en,pt-br)?

**Comment by khaosdoctor** [comment]
Vamos manter só o summary e o link para o contributing

**Comment by khaosdoctor** [comment]
Sim então, no Readme vai ter a lista de todos os links e cada link aponta para um arquivo do comando, o que acha?

**Comment by khaosdoctor** [comment]
Os conteúdos do Readme seriam 
- Lista de conteúdos (links para os arquivos) 
- Link para o contributing 

Ai já evitaríamos problemas com as PR e também com conflitos porque só quem é o dono do repositório mexeria nesse arquivo, a pessoa que fez a PR colocaria só o arquivo de comando e depois da aprovação o dono faria o link. Assim criamos um fluxo tambem.

**Comment by darlanmendonca** [comment]
concordo c td, só sinto falta d no início da lista de conteúdos, ter uma lista de comandos básicos, realmente básicos, q minha mãe entenda rs, lista de básicos
- pwd
- cd
- ls
- mkdir
- touch
- rm
- man

e axo q só, pq se listarmos tds em uma única lista, sinto q pra quem steja pla primeira vez, se assuste, ou tenha dificuldad em algo

**Comment by khaosdoctor** [comment]
Mas é isso mesmo, a gente vai organizar a lista de comandos, ai até e o tópico desse issue, porque criariamos um índice organizado ou por complexidade, que teria seus comandos que vc me mandou acima ou alfabeticamente...

**Comment by khaosdoctor** [comment]
O Readme seria o índice, a porta de entrada ai poderíamos adicionar em ordem didática, alfabética ou complexidade. Dentro de cada arquivo o link para o próximo e o anterior

**Comment by khaosdoctor** [comment]
Como uma wiki mesmo kk

**Comment by odineiramone** [comment]
Essa idéia de ficar como uma wiki é bem legal mesmo! E em cada arquivo com o comando, pode ter um link de voltar para o README com a lista de comandos

**Comment by khaosdoctor** [comment]
Justamente, montamos um fluxo de arquivos e um fluxo de visualização, é uma boa ideia para se começar.

O commiter da PR vai mandar apenas o comando, alguém da organização junta e coloca no padrão

**Comment by darlanmendonca** [comment]
mas eu creio q devamos ter poucos itens numa lista basica, q tipo, quem ta começando, gravar 5 comandos é bastante coisa, daí quando o mesmo ja gravou tais comandos, esta se sentindo confortável quanto a estes, ele volta e ve o restante da lista

ter duas listas no readme, uma basica (c uns 5 comandos), e na sequência uma full (em ordem alfabética) e sendo a mesma editada por nós, após PR's, creio ser uma boa

ou n curtem a idéia de uma lista básica?

**Comment by khaosdoctor** [comment]
Eu sou mais a favor de manter o readme como o _Table of Contents_, porque se tivermos duas listas separadas a pessoa acaba se perdendo, acho legal pra sanar os dois problemas de uma vez, fazermos uma única lista ordenada por complexidade e didática, ou seja, os comandos mais simples primeiro para que o usuário possa começar seguindo a ordem, do 1 aos demais.

**Comment by darlanmendonca** [comment]
n concordo, mas tipo, to na dúvida/ponderando entre ambas, rs

**Comment by khaosdoctor** [comment]
Podemos fazer o seguinte, crie uma PR com o seu modelo de README e ai vamos discutindo em cima dele, o que acha?

**Comment by darlanmendonca** [comment]
boua!! farei

**Comment by darlanmendonca** [comment]
here https://github.com/knowledge-club/bash/pull/25

**Comment by khaosdoctor** [comment]
Indo para #25
