### ISSUE TITLE
Ruby basics

### ISSUE THREAD

**Issue by odineiramone** [darlanmendonca/bash-basics#12]
Me proponho a fazer um basics de ruby mas gostaria de saber se seria relevante. Na internet existem vários tutoriais bem curtos de Ruby como o Ruby em 20 Minutos e o Try Ruby (Code School) então, não sei se um ruby-basics aqui no knowledge-club seria relevante

**Comment by khaosdoctor** [comment]
@OdineiRibeiro leva esse issue para o repositório universal por favor, assim fica mais centralizado 😄 

Aqui o link https://github.com/knowledge-club/knowledge-club/issues
