### ISSUE TITLE
CONTRIBUTING

### ISSUE THREAD

**Issue by darlanmendonca** [darlanmendonca/bash-basics#13]
q tal? @khaosdoctor @WendellAdriel 

Gostou do conteúdo e quer contribuir? Adoraríamos sua ajuda, assim construímos conteúdos realmente relevantes, útil para quem está começando, e também para nós que continuamente estamos sempre aprendendo.

Nosso objetivo é listar coisas de forma
- didática
- com exemplos
- e com atividades quando possível

Didática e exemplos ajudam a entender, que é o mais importante.
Atividades ajudam a fixar o conteúdo em mente, se não não adianta :D.
### Como contribuir

A fim de facilitar contribuições e revisões, precisamos nos organizar. Juntos definimos alguns processos para contribuirmos de forma fácil e evitando possíveis erros:
1. Dê fork no projeto
2. Crie uma branch, para adicionar sua contribuição 
3. Faça um tipo apenas de contribuição por vez
4. Faça uma pull request

Por um tipo apenas quero dizer, evite adicionar muitos comandos de uma só vez. Exemplo, vou contribuir com os novos comandos `rm`, e `mv`. Então devem ser dois pull requests, e não apenas um. Isto além de facilitar o code review, também irá evitar conflitos, e facilitar correções necessárias.
### Organização

Quando for adicionar um novo comando, crie um arquivo markdown, exemplo `rm.md`, e em tal arquivo, aborde o mesmo.
No `Readme.md` listamos apenas os comando realmente básicos/essenciais para quem está começando. 
Demais comandos, são listados no arquivo `summary.md`, e ordenados em ordem alfabética.

Ou seja, quando for contribuir com um novo comando
1. Crie um arquivo para o mesmo (exemplo: `rm.md`).
2. Adicione o link para o mesmo em `summary.md`, em ordem alfabética.
3. Ou adicione no `Readme.md` se realmente for básico/essencial.

**Comment by darlanmendonca** [comment]
aprovando o texto, colocamos em inglês

**Comment by pitalig** [comment]
Acho que seria legal também preparar um arquivo markdown pra servir como modelo pra quando alguém for adicionar um comando, se gostarem da ideia, posso cuidar disso...

**Comment by darlanmendonca** [comment]
ahh sim com ctz!! vamos colocar em um CONTRIBUTING.md c ctz, daw qdo darem PR, irá aparecer o arquivo. E no readme tbm iremos fazer menção para o contributing.md.

neste momento ajuda nós a aprovar o contributing, creio q será mais produtivo
dawe aprovado, vamos trampando em conteúdo ou outras idéias q surgirem

**Comment by pitalig** [comment]
Sobre o contributing acho que está ótimo! :)

**Comment by darlanmendonca** [comment]
@pituca292 perfect!!!
criei uma PR, traduzido em inglês, galera aprovando, subimos

provavel q só corrijamos algum erro ortográfico, rs.

**Comment by darlanmendonca** [comment]
the pull request https://github.com/knowledge-club/bash/pull/14

**Comment by khaosdoctor** [comment]
Vou fechar em favor da https://github.com/knowledge-club/knowledge-club/issues/3

**Comment by WendellAdriel** [comment]
grandes ideias
