### ISSUE TITLE
Flag -a meaning

### ISSUE THREAD

**Issue by weber97** [darlanmendonca/bash-basics#26]
Hello, in the "ls" guidelines -> https://github.com/knowledge-club/bash/blob/master/content/pt-br/ls.md

It would be nice to tell that the flag -a means "all".

Nice project, congratulations.

**Comment by darlanmendonca** [comment]
thansk again @weber97, we add the PR https://github.com/knowledge-club/bash/pull/29

**Comment by darlanmendonca** [comment]
applied
