### ISSUE TITLE
Compound name directory

### ISSUE THREAD

**Issue by weber97** [darlanmendonca/bash-basics#27]
Hi guys, in the MKDIR guidelines -> https://github.com/knowledge-club/bash/blob/master/content/pt-br/mkdir.md

it's nice to say that we can use quotes to create a dir with a compound name.

Example: 
mkdir directory\ with\ spaces 
mkdir "directory with spaces"

**Comment by darlanmendonca** [comment]
thansk @weber97, I create a PR https://github.com/knowledge-club/bash/pull/28

**Comment by darlanmendonca** [comment]
applied
