### ISSUE TITLE
order

### ISSUE THREAD

**Issue by darlanmendonca** [darlanmendonca/bash-basics#3]
@khaosdoctor What you think about order commands?

I'm thinking in order by complexity, in example below, I fall with whereis and which
- PWD
- CD
- MKDIR
- LS
- TOUCH
- RM
- CAT
- ECHO
- MAN
- WHEREIS
- WHICH

**Comment by khaosdoctor** [comment]
I think it would be a good ordering factor but, in my opinion, the order should be:
- MAN
- PWD
- ECHO
- CD
- LS
- MKDIR
- CAT
- TOUCH
- RM
- WHEREIS
- WHICH

Grouping by complexity and by action

**Comment by darlanmendonca** [comment]
I like!! 
But I dont agree with `echo`, they  is so relevant in a list like that? I'm javascript developer, and I use console.log every time, echo is similar in uses?

**Comment by khaosdoctor** [comment]
Well, echo is not just used to display a message, but it can also pass piped parameters to other commands, such as a file creation for instance:

``` sh
echo "the content" >> thefile.md
```

**Comment by darlanmendonca** [comment]
yep, but I guess that approach (pipes) is more complicated for beginners, so I vote to fall with echo to after rm, or bottom of list, what you think?

**Comment by khaosdoctor** [comment]
Well, thinking that way it is a good approach, maybe I could improve the echo command to include explanations and use of pipes instead of just the echo itself

**Comment by darlanmendonca** [comment]
Yep, pipes examples will be nice, but I continue thinking that in bottom of list

**Comment by khaosdoctor** [comment]
I agree with the position as well, when I reorder according to #4 I'll get to this as well
