### ISSUE TITLE
Changes are gone

### ISSUE THREAD

**Issue by WendellAdriel** [darlanmendonca/bash-basics#8]
Most of the changes I made with my PR is gone.

**Comment by darlanmendonca** [comment]
:(, my bad in merge

I will see what I lost, and fix that.
We will move the repo to an organization and fix all

**Comment by WendellAdriel** [comment]
It's ok!!! Thanks!!!

**Comment by khaosdoctor** [comment]
I think the changes are still there, at least all the commands are present 😮

**Comment by darlanmendonca** [comment]
the explanation of commands in @WendellAdriel PR, I lost in the merge, I keep only your. my bad

**Comment by khaosdoctor** [comment]
Oh yes! I haven't noticed it

**Comment by darlanmendonca** [comment]
we will improve the articles, instead a single markdown, using readme as a summary, and articles to each command, this will help to avoid future conflicts

**Comment by khaosdoctor** [comment]
You will put it on the specs of #9 then?

**Comment by darlanmendonca** [comment]
yep, lets close this Issue, and begin right with https://github.com/knowledge-club/bash-basics/issues/9
