### ISSUE TITLE
define BASICS

### ISSUE THREAD

**Issue by darlanmendonca** [darlanmendonca/bash-basics#9]
@WendellAdriel @khaosdoctor creio ique nós devemos manter no repositório APENAS comandos básico, OU, separar melhor os básicos dos posteriores, para ter uma ordem de dificuldade.

Minha sugestão
- renomear o repo para apenas 'bash'
- manter no readme, apenas uns poucos comandos, realmente básicos pra quem está começando
- demais comandos, serem separados em demais arquivos markdown, permitindo fazer até um artigo sobre um determinado comando
- linkar kda "artigo" no readme.md

minha referência (embora bati o olho rapidamente, creio q tem mais referências nesse mesmo e em outros repos) foi este https://github.com/loverajoel/jstips

**Comment by darlanmendonca** [comment]
ahh, kda PR, seria apenas d um comando, evitando conflitos d multiplas pull requests

**Comment by khaosdoctor** [comment]
É uma boa ideia, eu concordo com renomear os repositórios de temas (aqueles que falam sobre a tecnologia, ex: Docker, Bash, git) somente com o nome da tecnologia e sem especificar nada na frente (como bash-basics).

Na questão do readme eu acho que a gente poderia fazer uma coisa ainda mais simples, como nesse caso aqui https://github.com/IonicBrazil/ionic2-docs, aonde o readme é basicamente o sumário e cada link manda para um arquivo dentro do repo.

A gente poderia organizar da seguinte maneira: 
- O README.md seria o sumário
- No fim do readme haveria _sempre_ uma nota de contribuição para auxiliar novos membros a como participar
- Juntamente com a nota de contribuição podemos colocar também como contribuir naquele repositório específico ou criar um outro arquivo explicando a organização geral (talvez até um outro repo a parte para tratar só das organizações dentro dos repos)
- Dentro de cada readme teriam vários arquivos Markdown com o conteúdo proposto

Dessa forma acho que podemos categorizar tanto em dificuldades quanto em temas e também poderíamos separar melhor tudo que está dentro. Sem falar que se tivermos um pages, podemos separar e categorizar melhor.

**Comment by khaosdoctor** [comment]
Com relação às PR's eu concordo, cada PR deve ser relativa a apenas um comando, em um arquivo separado porque ai diminuímos ainda mais a chance de erros e conflitos

**Comment by darlanmendonca** [comment]
blz, definiremos o contributing em https://github.com/knowledge-club/bash/issues/13#issuecomment-251669356

**Comment by WendellAdriel** [comment]
boas ideias!!!
